param = [
        # "gcc CFLAGS  = -O0",
        # "gcc CFLAGS  = -O1",
        # "gcc CFLAGS  = -O2",
        # "gcc CFLAGS  = -O2 -march=native",
        # "gcc CFLAGS  = -O3",
        # "gcc CFLAGS  = -O3 -march=native",
        # "gcc CFLAGS  = -O3 -ffast-math",
        # "gcc CFLAGS  = -O3 -funroll-loops",
        # "gcc CFLAGS  = -O3 -funswitch-loops",
        # "gcc CFLAGS  = -O3 -floop-block",
        # "gcc CFLAGS  = -O3 -march=native -DN=512",
        # "gcc CFLAGS  = -O3 -march=native -DN=1024",
        # "gcc-10 CFLAGS  = -O0",
        # "gcc-10 CFLAGS  = -O1",
        # "gcc-10 CFLAGS  = -O2",
        # "gcc-10 CFLAGS  = -O2 -march=native",
        # "gcc-10 CFLAGS  = -O3",
        # "gcc-10 CFLAGS  = -O3 -march=native",
        # "gcc-10 CFLAGS  = -O3 -ffast-math",
        # "gcc-10 CFLAGS  = -O3 -funroll-loops",
        # "gcc-10 CFLAGS  = -O3 -funswitch-loops",
        # "gcc-10 CFLAGS  = -O3 -floop-block\n",
        # "gcc-10 CFLAGS  = -O3 -floop-block -DN=512\n",
        # "gcc-10 CFLAGS  = -O3 -floop-block -DN=1024\n",
        # "gcc-10 CFLAGS  = -O3 -march=native -DN=512",
        # "gcc-10 CFLAGS  = -O3 -march=native -DN=1024",
        "CFLAGS  = -O3 -march=native -DN=300\n",
        "CFLAGS  = -O3 -march=native -DN=356\n",
        "CFLAGS  = -O3 -march=native -DN=400\n",
        "CFLAGS  = -O3 -march=native -DN=500\n",
        "CFLAGS  = -O3 -march=native -DN=600\n",
        "CFLAGS  = -O3 -march=native -DN=700\n",
        "CFLAGS  = -O3 -march=native -DN=800\n",
        "CFLAGS  = -O3 -march=native -DN=900\n",
        "CFLAGS  = -O3 -march=native -DN=1000\n",
        # "clang CFLAGS  = -O0",
        # "clang CFLAGS  = -O1",
        # "clang CFLAGS  = -O2",
        # "clang CFLAGS  = -O2 -march=native",
        # "clang CFLAGS  = -O3",
        # "clang CFLAGS  = -O3 -march=native",
        # "clang CFLAGS  = -O3 -ffast-math",
        # "clang CFLAGS  = -O3 -funroll-loops",
        # "clang CFLAGS  = -O3 -funswitch-loops",
        # # "clang CFLAGS  = -O3 -floop-block",  # doesn't work on clang
        # "clang CFLAGS  = -O3 -march=native -DN=512",
        # "clang CFLAGS  = -O3 -march=native -DN=1024",
        # " -icc CFLAGS  = -O0\n",
        # " -icc CFLAGS  = -O1\n",
        # " -icc CFLAGS  = -O2\n",
        # " -icc CFLAGS  = -O2 -xHost\n",
        # " -icc CFLAGS  = -O3\n",
        # " -icc CFLAGS  = -O3 -xHost\n",
        # " -icc CFLAGS  = -O3 -fp-model fast=2 -no-prec-div\n",
        # " -icc CFLAGS  = -O3 -funroll-loops\n",
        # " -icc CFLAGS  = -O3 -funswitch-loops\n",
        # # -icc CFLAGS  = -O3 -floop-block\n", # doesn't work on icc
        # " -icc CFLAGS  = -O3 -xHost -DN=512\n",
        # " -icc CFLAGS  = -O3 -xHost -DN=1024\n",
]
